USE RestaurantDB;

CREATE TABLE Restuarant_Name (
	OBJECTID INT PRIMARY KEY,
    RESTAURANTNAME VARCHAR(50),
    ADDRESS VARCHAR(50),
    CITY VARCHAR(25),
    STATE VARCHAR(3),
    POSTALCODE INT
    );

CREATE TABLE Inspection(
	OBJECTID INT PRIMARY KEY,
    SCORE INT,
    INSPECTIONTYPE VARCHAR(25),
    DESCRIPTION VARCHAR(500)
    );


SELECT Restuarant_Name.OBJECTID, Restuarant_Name.RESTAURANTNAME, Restuarant_Name.ADDRESS, Restuarant_Name.CITY, Restuarant_Name.STATE, Restuarant_Name.POSTALCODE,
Inspection.SCORE, Inspection.INSPECTIONTYPE, Inspection.DESCRIPTION
FROM Restuarant_Name
JOIN Inspection
ON Restuarant_Name.OBJECTID = Inspection.OBJECTID;

ALTER TABLE Restuarant_Name RENAME TO  Restaurant_Name; 

SELECT * 
FROM Restaurant_Name; 

ALTER TABLE Restaurant_Name MODIFY COLUMN POSTALCODE  VARCHAR(20);    

ALTER TABLE Restaurant_Name MODIFY COLUMN RESTAURANTNAME VARCHAR(100);    

ALTER TABLE Inspection MODIFY COLUMN DESCRIPTION VARCHAR(5000);    